/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CommentsTipsGUI.java
 *
 * Created on Oct 30, 2011, 6:15:16 PM
 */

package com.edinarobotics.gui;

/*
 * @author aoneill
 * @note Made by the Netbeans built-in GUI creator
 */
public class CommentsTipsGUI extends javax.swing.JFrame
{

    /** Creates new form CommentsTipsGUI */
    public CommentsTipsGUI()
    {
        initComponents();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textContainer = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comments");
        setResizable(false);

        textArea.setColumns(20);
        textArea.setEditable(false);
        textArea.setRows(5);
        textArea.setText("       -- == Things To Record in The Comments == --\n1. Robot Structure: Consistently executes its task well?  \nWeaknesses? Flaws? Unique Features? Malfunctions?\n2. Team Friendliness (jerks or friends?)\n3. Adaptability: (of team and/or robot) Can they play offense? \n       Defense? Both? Switch if asked? Are they selfish or not\n4. Drivers - Is there a set group of drivers? How do the drive \n       teams interact with each other?\n5. Think of additional comments and other notes");
        textContainer.setViewportView(textArea);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(textContainer, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 402, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(textContainer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommentsTipsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea textArea;
    private javax.swing.JScrollPane textContainer;
    // End of variables declaration//GEN-END:variables

}
