/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IndividualGUI.java
 *
 * Created on Mar 7, 2012, 11:50:36 AM
 */

package com.edinarobotics.gui;

import com.edinarobotics.filer.*;
import com.edinarobotics.gui.utilities.*;
import com.edinarobotics.scout.Main;
import com.sun.org.apache.bcel.internal.generic.ISTORE;
import java.util.ArrayList;

/*
 * @author aoneill
 * @note Made by the Netbeans built-in GUI creator
 */
public class IndividualGUI extends javax.swing.JFrame
{
    // Declare default feild fillers
    private final static String teamNumberDText = "Team ##";
    private final static String penaltiesBoxDText = "Penalties";
    private final static String NOTHING = null;

    private static final String DATA_SEPARATOR = Main.DATA_SEPARATOR;
    private static final String teamDir = Main.teamFileDir;
    private static final String commentDir = Main.commentFileDir;

    // Create arrays to store the data in the feilds
    private int teamNumber;
    private int teamScoreArray[] = new int[3];
    private String teamPenalties;
    private String comments;
    private int matchCount = 0;
    private int currentMatch = 0;


    /** Creates new form IndividualGUI */
    public IndividualGUI()
    {
        initComponents();
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teamPanel = new javax.swing.JPanel();
        teamNumberBox = new javax.swing.JTextField();
        penaltiesBox = new javax.swing.JTextField();
        commentsPane = new javax.swing.JScrollPane();
        commentsArea = new javax.swing.JTextArea();
        commentsLabel = new javax.swing.JLabel();
        tabbedPane = new javax.swing.JTabbedPane();
        auto = new javax.swing.JPanel();
        topLabel = new javax.swing.JLabel();
        leftLabel = new javax.swing.JLabel();
        rightLabel = new javax.swing.JLabel();
        bottomLabel = new javax.swing.JLabel();
        leftTextBox = new javax.swing.JTextField();
        rightTextBox = new javax.swing.JTextField();
        bottomTextBox = new javax.swing.JTextField();
        topTextBox = new javax.swing.JTextField();
        main = new javax.swing.JPanel();
        topLabel1 = new javax.swing.JLabel();
        leftLabel1 = new javax.swing.JLabel();
        rightLabel1 = new javax.swing.JLabel();
        bottomLabel1 = new javax.swing.JLabel();
        leftTextBox1 = new javax.swing.JTextField();
        rightTextBox1 = new javax.swing.JTextField();
        bottomTextBox1 = new javax.swing.JTextField();
        topTextBox1 = new javax.swing.JTextField();
        end = new javax.swing.JPanel();
        topLabel2 = new javax.swing.JLabel();
        leftLabel2 = new javax.swing.JLabel();
        rightLabel2 = new javax.swing.JLabel();
        bottomLabel2 = new javax.swing.JLabel();
        leftTextBox2 = new javax.swing.JTextField();
        rightTextBox2 = new javax.swing.JTextField();
        bottomTextBox2 = new javax.swing.JTextField();
        topTextBox2 = new javax.swing.JTextField();
        balanceCheck = new javax.swing.JCheckBox();
        roundPanel = new javax.swing.JPanel();
        roundLabel = new javax.swing.JLabel();
        roundInput = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        teamPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 3));

        teamNumberBox.setColumns(6);
        teamNumberBox.setText("Team ##");
        teamNumberBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamNumberBoxMouseClicked(evt);
            }
        });

        penaltiesBox.setText("Penalties");
        penaltiesBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penaltiesBoxMouseClicked(evt);
            }
        });

        commentsArea.setColumns(20);
        commentsArea.setLineWrap(true);
        commentsArea.setRows(5);
        commentsPane.setViewportView(commentsArea);

        commentsLabel.setText("Additional Comments");

        tabbedPane.setFont(new java.awt.Font("Tahoma", 0, 10));

        topLabel.setText("Top");

        leftLabel.setText("Left");

        rightLabel.setText("Right");

        bottomLabel.setText("Bottom");

        leftTextBox.setColumns(3);

        rightTextBox.setColumns(3);

        bottomTextBox.setColumns(4);

        topTextBox.setColumns(4);

        org.jdesktop.layout.GroupLayout autoLayout = new org.jdesktop.layout.GroupLayout(auto);
        auto.setLayout(autoLayout);
        autoLayout.setHorizontalGroup(
            autoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(autoLayout.createSequentialGroup()
                .add(leftTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(7, 7, 7)
                .add(bottomLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rightTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(autoLayout.createSequentialGroup()
                .add(10, 10, 10)
                .add(leftLabel)
                .add(18, 18, 18)
                .add(autoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(autoLayout.createSequentialGroup()
                        .add(13, 13, 13)
                        .add(topLabel))
                    .add(autoLayout.createSequentialGroup()
                        .add(topTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rightLabel))))
            .add(autoLayout.createSequentialGroup()
                .add(49, 49, 49)
                .add(bottomTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        autoLayout.setVerticalGroup(
            autoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(autoLayout.createSequentialGroup()
                .add(autoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(leftLabel)
                    .add(autoLayout.createSequentialGroup()
                        .add(topLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(topTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(rightLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(autoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(leftTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(rightTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(bottomLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bottomTextBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        tabbedPane.addTab("Autonomous", auto);

        topLabel1.setText("Top");

        leftLabel1.setText("Left");

        rightLabel1.setText("Right");

        bottomLabel1.setText("Bottom");

        leftTextBox1.setColumns(3);

        rightTextBox1.setColumns(3);

        bottomTextBox1.setColumns(4);

        topTextBox1.setColumns(4);

        org.jdesktop.layout.GroupLayout mainLayout = new org.jdesktop.layout.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainLayout.createSequentialGroup()
                .add(leftTextBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(7, 7, 7)
                .add(bottomLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rightTextBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(mainLayout.createSequentialGroup()
                .add(10, 10, 10)
                .add(leftLabel1)
                .add(18, 18, 18)
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(mainLayout.createSequentialGroup()
                        .add(13, 13, 13)
                        .add(topLabel1))
                    .add(mainLayout.createSequentialGroup()
                        .add(topTextBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rightLabel1))))
            .add(mainLayout.createSequentialGroup()
                .add(49, 49, 49)
                .add(bottomTextBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(mainLayout.createSequentialGroup()
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(leftLabel1)
                    .add(mainLayout.createSequentialGroup()
                        .add(topLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(topTextBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(rightLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(mainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(leftTextBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(rightTextBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(bottomLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bottomTextBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        tabbedPane.addTab("Main Game", main);

        topLabel2.setText("Top");

        leftLabel2.setText("Left");

        rightLabel2.setText("Right");

        bottomLabel2.setText("Bottom");

        leftTextBox2.setColumns(3);

        rightTextBox2.setColumns(3);

        bottomTextBox2.setColumns(4);

        topTextBox2.setColumns(4);

        balanceCheck.setText("Balanced");

        org.jdesktop.layout.GroupLayout endLayout = new org.jdesktop.layout.GroupLayout(end);
        end.setLayout(endLayout);
        endLayout.setHorizontalGroup(
            endLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(endLayout.createSequentialGroup()
                .add(leftTextBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(7, 7, 7)
                .add(bottomLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rightTextBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(endLayout.createSequentialGroup()
                .add(10, 10, 10)
                .add(leftLabel2)
                .add(18, 18, 18)
                .add(endLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(endLayout.createSequentialGroup()
                        .add(13, 13, 13)
                        .add(topLabel2))
                    .add(endLayout.createSequentialGroup()
                        .add(topTextBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 58, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rightLabel2))))
            .add(endLayout.createSequentialGroup()
                .add(49, 49, 49)
                .add(bottomTextBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(endLayout.createSequentialGroup()
                .add(34, 34, 34)
                .add(balanceCheck))
        );
        endLayout.setVerticalGroup(
            endLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(endLayout.createSequentialGroup()
                .add(endLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(leftLabel2)
                    .add(endLayout.createSequentialGroup()
                        .add(topLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(topTextBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(rightLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(endLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(endLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(leftTextBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(rightTextBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(bottomLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bottomTextBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(balanceCheck)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabbedPane.addTab("End Game", end);

        org.jdesktop.layout.GroupLayout teamPanelLayout = new org.jdesktop.layout.GroupLayout(teamPanel);
        teamPanel.setLayout(teamPanelLayout);
        teamPanelLayout.setHorizontalGroup(
            teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanelLayout.createSequentialGroup()
                .add(teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(teamPanelLayout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(teamNumberBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, teamPanelLayout.createSequentialGroup()
                            .add(11, 11, 11)
                            .add(penaltiesBox))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, teamPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .add(tabbedPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(commentsLabel)
                    .add(commentsPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        teamPanelLayout.setVerticalGroup(
            teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(commentsLabel)
                    .add(teamNumberBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(teamPanelLayout.createSequentialGroup()
                        .add(tabbedPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 198, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(penaltiesBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(commentsPane))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        roundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        roundLabel.setText("Round Number:");

        org.jdesktop.layout.GroupLayout roundPanelLayout = new org.jdesktop.layout.GroupLayout(roundPanel);
        roundPanel.setLayout(roundPanelLayout);
        roundPanelLayout.setHorizontalGroup(
            roundPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(roundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(roundLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(roundInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanelLayout.setVerticalGroup(
            roundPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(roundPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(roundInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(roundLabel))
        );

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(roundPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 29, Short.MAX_VALUE)
                .add(submitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(teamPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(24, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(roundPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(21, 21, 21))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(submitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(teamPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(65, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teamNumberBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamNumberBoxMouseClicked
        // TODO add your handling code here:
        textBoxSet(teamNumberBox, teamNumberDText);
}//GEN-LAST:event_teamNumberBoxMouseClicked

    private void penaltiesBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penaltiesBoxMouseClicked
        // TODO add your handling code here:
        textBoxSet(penaltiesBox, penaltiesBoxDText);
}//GEN-LAST:event_penaltiesBoxMouseClicked

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            ScoreUtility su = new ScoreUtility();

            // Get points for the teams
            int autoPoints = su.getScores(ScoreUtility.AUTO, topTextBox, leftTextBox, rightTextBox, bottomTextBox);
            int mainPoints = su.getScores(ScoreUtility.MAIN, topTextBox1, leftTextBox1, rightTextBox1, bottomTextBox1);
            int endPoints = su.getScores(ScoreUtility.END, topTextBox2, leftTextBox2, rightTextBox2, bottomTextBox2, balanceCheck);

            teamNumber = Integer.parseInt(teamNumberBox.getText());

            // Store scores for Team #1
            //System.out.println("Storing Scores for Team #1");
            teamScoreArray[0] = autoPoints;
            teamScoreArray[1] = mainPoints;
            teamScoreArray[2] = endPoints;

            // Store penalties for all teams
            //System.out.println("Storing Penalties...");
            teamPenalties = penaltiesBox.getText();

            // Store commentsArea for all teams
            //System.out.println("Storing Comments...");
            comments = commentsArea.getText();

            // Store the current match
            currentMatch = Integer.parseInt(roundInput.getText());

            // If the current match is less than or equal to 0, throw an exception
            if(currentMatch <= 0)
            {
                ErrorGUI eGUI = new ErrorGUI("Round Number Negative!", ErrorGUI.ERROR_SEVERE);
            }

            matchCount++;

            // If the number of teams recorded is at least 6, reset the count and increase the match` number
            if(matchCount > 6)
            {
                // Incriment the current match
                currentMatch++;

                // Reset the internal team count
                matchCount = 0;
            }

            // reset all the fields!
            resetFields();

            // Store the new Match number
            roundInput.setText(Integer.toString(currentMatch));

            // If the penalties for a team equal null or the default text, replace the penalties with "none"
            if(teamPenalties.equals(penaltiesBoxDText) || teamPenalties.equals(""))
            {
                teamPenalties = "none";
            }

            addScoreData();
            addCommentData();
        }

        // If a feild was empty or something failed, reset the submitted button, and tell the console
        catch (Exception e)
        {
            e.printStackTrace();
            ErrorGUI eGUI = new ErrorGUI("Bad Submission!", ErrorGUI.ERROR_LOW);
        }
}//GEN-LAST:event_submitButtonActionPerformed

    public void resetFields()
    {
        topTextBox.setText(NOTHING);
        topTextBox1.setText(NOTHING);
        topTextBox2.setText(NOTHING);

        leftTextBox.setText(NOTHING);
        leftTextBox1.setText(NOTHING);
        leftTextBox2.setText(NOTHING);

        rightTextBox.setText(NOTHING);
        rightTextBox1.setText(NOTHING);
        rightTextBox2.setText(NOTHING);

        bottomTextBox.setText(NOTHING);
        bottomTextBox1.setText(NOTHING);
        bottomTextBox2.setText(NOTHING);

        penaltiesBox.setText(NOTHING);
        commentsArea.setText(NOTHING);

        teamNumberBox.setText(NOTHING);
    }

    private void textBoxSet(javax.swing.JTextField box, String defaultText)
    {
        String previous = box.getText();
        box.setText(box.getText().equals(defaultText) ? NOTHING : previous);
    }

    private void addScoreData()
    {
        FileScanner scan = new FileScanner();
        FileCreator fileCreo = new FileCreator();

        String teamFile = teamNumber + ".txt";

        if(!scan.isFileCreated(teamDir, teamFile))
        {
            fileCreo.createFile(teamDir, teamFile);
            fileCreo.addTeamHeader();
            fileCreo.closeFile();
        }

        scan.openFile(teamDir, teamFile);

        ArrayList<String> list = new ArrayList<String>();

        while(scan.hasNextEntry())
        {
            list.add(scan.getNextLine());
        }

        list.add(String.format("%d%s%d%s%d%s%d%s%s%s", currentMatch, DATA_SEPARATOR, teamScoreArray[0], DATA_SEPARATOR, teamScoreArray[1], DATA_SEPARATOR, teamScoreArray[2], DATA_SEPARATOR, teamPenalties, System.getProperty("line.separator")));

        fileCreo.openFile(teamDir, teamFile);
        for(int i = 0; i < list.size(); i++)
        {
            String entry = (String) list.get(i).toString();
            fileCreo.addEntry(entry);
        }
        
        fileCreo.closeFile();
    }

    private void addCommentData()
    {
        FileScanner scan = new FileScanner();
        FileCreator fileCreo = new FileCreator();

        String teamFile = teamNumber + "-Comments.txt";

        if(scan.isFileCreated(commentDir, teamFile))
        {
            scan.openFile(commentDir, teamFile);

            ArrayList<String> list = new ArrayList<String>();

            while(scan.hasNextEntry())
            {
                list.add(scan.getNextLine());
            }

            list.add(NOTHING);
            list.add("#########################");
            list.add(String.format("Round: %d", currentMatch));
            list.add(NOTHING);

            list.add(comments);

            fileCreo.openFile(commentDir, teamFile);
            for(int i = 0; i < list.size(); i++)
            {
                String entry = (String) list.get(i).toString();
                fileCreo.addEntry(entry);
            }

            fileCreo.closeFile();
        }
        else
        {
            fileCreo.createFile(commentDir, teamFile);
            fileCreo.addCommentHeader();
            fileCreo.closeFile();

            scan.openFile(commentDir, teamFile);

            ArrayList<String> list = new ArrayList<String>();

            while(scan.hasNextEntry())
            {
                list.add(scan.getNextLine());
            }

            list.add(comments);

            fileCreo.openFile(commentDir, teamFile);
            for(int i = 0; i < list.size(); i++)
            {
                String entry = (String) list.get(i).toString();
                fileCreo.addEntry(entry);
            }
            
            fileCreo.closeFile();
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndividualGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel auto;
    private javax.swing.JCheckBox balanceCheck;
    private javax.swing.JLabel bottomLabel;
    private javax.swing.JLabel bottomLabel1;
    private javax.swing.JLabel bottomLabel2;
    private javax.swing.JTextField bottomTextBox;
    private javax.swing.JTextField bottomTextBox1;
    private javax.swing.JTextField bottomTextBox2;
    private javax.swing.JTextArea commentsArea;
    private javax.swing.JLabel commentsLabel;
    private javax.swing.JScrollPane commentsPane;
    private javax.swing.JPanel end;
    private javax.swing.JLabel leftLabel;
    private javax.swing.JLabel leftLabel1;
    private javax.swing.JLabel leftLabel2;
    private javax.swing.JTextField leftTextBox;
    private javax.swing.JTextField leftTextBox1;
    private javax.swing.JTextField leftTextBox2;
    private javax.swing.JPanel main;
    private javax.swing.JTextField penaltiesBox;
    private javax.swing.JLabel rightLabel;
    private javax.swing.JLabel rightLabel1;
    private javax.swing.JLabel rightLabel2;
    private javax.swing.JTextField rightTextBox;
    private javax.swing.JTextField rightTextBox1;
    private javax.swing.JTextField rightTextBox2;
    private javax.swing.JTextField roundInput;
    private javax.swing.JLabel roundLabel;
    private javax.swing.JPanel roundPanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField teamNumberBox;
    private javax.swing.JPanel teamPanel;
    private javax.swing.JLabel topLabel;
    private javax.swing.JLabel topLabel1;
    private javax.swing.JLabel topLabel2;
    private javax.swing.JTextField topTextBox;
    private javax.swing.JTextField topTextBox1;
    private javax.swing.JTextField topTextBox2;
    // End of variables declaration//GEN-END:variables

}
