/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsGUI.java
 *
 * Created on Nov 3, 2011, 9:13:40 PM
 */

package com.edinarobotics.gui;

import com.edinarobotics.data.ConfigFile;
import com.edinarobotics.logger.Logger;
import com.edinarobotics.scout.Main;
import java.io.File;
import java.util.logging.Level;

/*
 * @author aoneill
 * @note Made by the Netbeans built-in GUI creator
 */


public class SettingsGUI extends javax.swing.JFrame
{
    private static String LOG_TAG = "SettingsGUI";

    private static Logger log = Main.log;
    private static ConfigFile config = new ConfigFile();

    private static String selectedWorkspaceDir;
    private static boolean logSetting;

    /** Creates new form SettingsGUI */
    public SettingsGUI()
    {
        String[] configData = config.configRead();
        selectedWorkspaceDir = configData[0];
        logSetting = Boolean.parseBoolean(configData[1]);

        setTeamDirField(selectedWorkspaceDir);
        setLogBox(logSetting);

        initComponents();

        fileExplorer = new javax.swing.JFileChooser();
        fileExplorer.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        
        setVisible(true);

        log.setEnabled(logSetting);
        log.log();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logCheckBox = new javax.swing.JCheckBox();
        scoutButton = new javax.swing.JButton();
        wDirPanel = new javax.swing.JPanel();
        teamDirLocation = new javax.swing.JTextField();
        chooseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        logCheckBox.setText("Log Session");
        logCheckBox.setFocusable(false);

        scoutButton.setText("Scout!");
        scoutButton.setFocusable(false);
        scoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoutButtonActionPerformed(evt);
            }
        });

        wDirPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Workspace Directory"));

        teamDirLocation.setColumns(50);
        teamDirLocation.setFont(new java.awt.Font("Lucida Grande", 0, 10));
        teamDirLocation.setFocusable(false);

        chooseButton.setText("Choose ...");
        chooseButton.setFocusable(false);
        chooseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout wDirPanelLayout = new org.jdesktop.layout.GroupLayout(wDirPanel);
        wDirPanel.setLayout(wDirPanelLayout);
        wDirPanelLayout.setHorizontalGroup(
            wDirPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(wDirPanelLayout.createSequentialGroup()
                .add(wDirPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(teamDirLocation, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, wDirPanelLayout.createSequentialGroup()
                        .addContainerGap(542, Short.MAX_VALUE)
                        .add(chooseButton)))
                .addContainerGap())
        );
        wDirPanelLayout.setVerticalGroup(
            wDirPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(wDirPanelLayout.createSequentialGroup()
                .add(teamDirLocation, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(chooseButton))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(logCheckBox)
                        .add(173, 173, 173)
                        .add(scoutButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(wDirPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(wDirPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(logCheckBox)
                    .add(scoutButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoutButtonActionPerformed
        // TODO add your handling code here:

        // Hide the GUI
        setVisible(false);

        // Update the Config File
        String[] update = {selectedWorkspaceDir, String.valueOf(logSetting)};
        config.configWrite(update);

        // Data Entry starts here
        new DataEntryGUI_4(Main.VERSION);
    }//GEN-LAST:event_scoutButtonActionPerformed

    private void chooseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseButtonActionPerformed
        // TODO add your handling code here:
        fileExplorer.setCurrentDirectory(new File(System.getProperty("user.dir")));
        
        int returnVal = fileExplorer.showOpenDialog(this);
        if(returnVal == javax.swing.JFileChooser.APPROVE_OPTION)
        {
            try
            {
                selectedWorkspaceDir = fileExplorer.getSelectedFile().getPath();
                teamDirLocation.setText(selectedWorkspaceDir);
            }
            catch(Exception e)
            {
                System.out.println("Could not set teamDirLocation Field!");
            }
        }
    }//GEN-LAST:event_chooseButtonActionPerformed

    private void setTeamDirField(String dirPath)
    {
        selectedWorkspaceDir = dirPath;
        teamDirLocation.setText(selectedWorkspaceDir);
    }

    private void setLogBox(boolean state)
    {
        logSetting = state;
        logCheckBox.setSelected(logSetting);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SettingsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chooseButton;
    private javax.swing.JCheckBox logCheckBox;
    private javax.swing.JButton scoutButton;
    private javax.swing.JTextField teamDirLocation;
    private javax.swing.JPanel wDirPanel;
    // End of variables declaration//GEN-END:variables

    private javax.swing.JFileChooser fileExplorer;
}
