/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataEntryGUI.java
 *
 * Created on Oct 30, 2011, 3:29:28 PM
 */

package org.scouting.gui;

import java.lang.Exception;
import java.util.Random;

/*
 * @author aoneill
 * @note Made by the Netbeans built-in GUI creator
 */
public class DataEntryGUI extends javax.swing.JFrame
{
    // Declare default feild fillers
    private final static String teamNumberDText = "Team ##";
    private final static String autoPointsDText = "Autonomous";
    private final static String endPointsDText = "End Game";
    private final static String mainPointsDText = "Main Game";
    private final static String penaltiesBoxDText = "Penalties";

    // Declare caps for random number generation
    private final static int RAND_AUTO_POINT_CAP = 12;
    private final static int RAND_END_POINT_CAP = 30;
    private final static int RAND_MAIN_POINT_CAP = 80;

    // Create arrays to store the data in the feilds
    private int teamNumberArray[] = new int[6];
    private int teamScoreArray[][] = new int[3][6];
    private String teamPenaltiesArray[] = new String[6];
    private String commentsArray[] = new String[6];
    private int currentMatch = 0;

    // Fla to store the state of the submit button
    private boolean submitted = false;


    /** Creates new form DataEntryGUI */
    public DataEntryGUI()
    {
        initComponents();

        // Show the window
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel = new javax.swing.JPanel();
        roundLabel = new javax.swing.JLabel();
        roundInput = new javax.swing.JTextField();
        teamPanel = new javax.swing.JPanel();
        teamNumber = new javax.swing.JTextField();
        pointsPanel = new javax.swing.JPanel();
        autoPoints = new javax.swing.JTextField();
        endPoints = new javax.swing.JTextField();
        mainPoints = new javax.swing.JTextField();
        penaltiesBox = new javax.swing.JTextField();
        commentsPane = new javax.swing.JScrollPane();
        comments = new javax.swing.JTextArea();
        commentsLabel = new javax.swing.JLabel();
        teamPanel1 = new javax.swing.JPanel();
        teamNumber1 = new javax.swing.JTextField();
        pointsPanel1 = new javax.swing.JPanel();
        autoPoints2 = new javax.swing.JTextField();
        endPoints2 = new javax.swing.JTextField();
        mainPoints2 = new javax.swing.JTextField();
        penaltiesBox1 = new javax.swing.JTextField();
        commentsPane1 = new javax.swing.JScrollPane();
        comments1 = new javax.swing.JTextArea();
        commentsLabel1 = new javax.swing.JLabel();
        teamPanel2 = new javax.swing.JPanel();
        teamNumber2 = new javax.swing.JTextField();
        pointsPanel2 = new javax.swing.JPanel();
        autoPoints3 = new javax.swing.JTextField();
        endPoints3 = new javax.swing.JTextField();
        mainPoints3 = new javax.swing.JTextField();
        penaltiesBox2 = new javax.swing.JTextField();
        commentsPane2 = new javax.swing.JScrollPane();
        comments2 = new javax.swing.JTextArea();
        commentsLabel2 = new javax.swing.JLabel();
        teamPanel3 = new javax.swing.JPanel();
        teamNumber3 = new javax.swing.JTextField();
        pointsPanel3 = new javax.swing.JPanel();
        autoPoints5 = new javax.swing.JTextField();
        endPoints5 = new javax.swing.JTextField();
        mainPoints5 = new javax.swing.JTextField();
        penaltiesBox3 = new javax.swing.JTextField();
        commentsPane3 = new javax.swing.JScrollPane();
        comments3 = new javax.swing.JTextArea();
        commentsLabel3 = new javax.swing.JLabel();
        teamPanel4 = new javax.swing.JPanel();
        teamNumber4 = new javax.swing.JTextField();
        pointsPanel4 = new javax.swing.JPanel();
        autoPoints6 = new javax.swing.JTextField();
        endPoints6 = new javax.swing.JTextField();
        mainPoints6 = new javax.swing.JTextField();
        penaltiesBox4 = new javax.swing.JTextField();
        commentsPane4 = new javax.swing.JScrollPane();
        comments4 = new javax.swing.JTextArea();
        commentsLabel4 = new javax.swing.JLabel();
        teamPanel5 = new javax.swing.JPanel();
        teamNumber5 = new javax.swing.JTextField();
        pointsPanel5 = new javax.swing.JPanel();
        autoPoints7 = new javax.swing.JTextField();
        endPoints7 = new javax.swing.JTextField();
        mainPoints7 = new javax.swing.JTextField();
        penaltiesBox5 = new javax.swing.JTextField();
        commentsPane5 = new javax.swing.JScrollPane();
        comments5 = new javax.swing.JTextArea();
        commentsLabel5 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        formatOption = new javax.swing.JMenuItem();
        commentsOption = new javax.swing.JMenuItem();
        aboutOption = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        clearOption = new javax.swing.JMenuItem();
        testOption = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Entry");
        setResizable(false);

        roundPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        roundLabel.setText("Round Number:");

        org.jdesktop.layout.GroupLayout roundPanelLayout = new org.jdesktop.layout.GroupLayout(roundPanel);
        roundPanel.setLayout(roundPanelLayout);
        roundPanelLayout.setHorizontalGroup(
            roundPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(roundPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(roundLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(roundInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 87, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundPanelLayout.setVerticalGroup(
            roundPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(roundPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(roundInput, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(roundLabel))
        );

        teamPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));

        teamNumber.setText("Team ##");
        teamNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamNumberMouseClicked(evt);
            }
        });

        pointsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Points"));

        autoPoints.setText("Autonomous");
        autoPoints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoPointsMouseClicked(evt);
            }
        });

        endPoints.setText("End Game");
        endPoints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endPointsMouseClicked(evt);
            }
        });

        mainPoints.setText("Main Game");
        mainPoints.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPointsMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pointsPanelLayout = new org.jdesktop.layout.GroupLayout(pointsPanel);
        pointsPanel.setLayout(pointsPanelLayout);
        pointsPanelLayout.setHorizontalGroup(
            pointsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pointsPanelLayout.createSequentialGroup()
                .add(autoPoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(endPoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(pointsPanelLayout.createSequentialGroup()
                .add(51, 51, 51)
                .add(mainPoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pointsPanelLayout.setVerticalGroup(
            pointsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pointsPanelLayout.createSequentialGroup()
                .add(pointsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(autoPoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(endPoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainPoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        penaltiesBox.setText("Penalties");
        penaltiesBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penaltiesBoxMouseClicked(evt);
            }
        });

        comments.setColumns(20);
        comments.setLineWrap(true);
        comments.setRows(5);
        commentsPane.setViewportView(comments);

        commentsLabel.setText("Additional Comments");

        org.jdesktop.layout.GroupLayout teamPanelLayout = new org.jdesktop.layout.GroupLayout(teamPanel);
        teamPanel.setLayout(teamPanelLayout);
        teamPanelLayout.setHorizontalGroup(
            teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanelLayout.createSequentialGroup()
                .add(teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(teamNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pointsPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(penaltiesBox))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(commentsLabel)
                    .add(commentsPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        teamPanelLayout.setVerticalGroup(
            teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanelLayout.createSequentialGroup()
                .add(teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(teamNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(commentsLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(teamPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, commentsPane)
                    .add(teamPanelLayout.createSequentialGroup()
                        .add(pointsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(penaltiesBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        teamPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));

        teamNumber1.setText("Team ##");
        teamNumber1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamNumber1MouseClicked(evt);
            }
        });

        pointsPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Points"));

        autoPoints2.setText("Autonomous");
        autoPoints2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoPoints2MouseClicked(evt);
            }
        });

        endPoints2.setText("End Game");
        endPoints2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endPoints2MouseClicked(evt);
            }
        });

        mainPoints2.setText("Main Game");
        mainPoints2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPoints2MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pointsPanel1Layout = new org.jdesktop.layout.GroupLayout(pointsPanel1);
        pointsPanel1.setLayout(pointsPanel1Layout);
        pointsPanel1Layout.setHorizontalGroup(
            pointsPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pointsPanel1Layout.createSequentialGroup()
                .add(autoPoints2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(endPoints2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(pointsPanel1Layout.createSequentialGroup()
                .add(51, 51, 51)
                .add(mainPoints2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pointsPanel1Layout.setVerticalGroup(
            pointsPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pointsPanel1Layout.createSequentialGroup()
                .add(pointsPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(autoPoints2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(endPoints2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainPoints2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        penaltiesBox1.setText("Penalties");
        penaltiesBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penaltiesBox1MouseClicked(evt);
            }
        });

        comments1.setColumns(20);
        comments1.setLineWrap(true);
        comments1.setRows(5);
        commentsPane1.setViewportView(comments1);

        commentsLabel1.setText("Additional Comments");

        org.jdesktop.layout.GroupLayout teamPanel1Layout = new org.jdesktop.layout.GroupLayout(teamPanel1);
        teamPanel1.setLayout(teamPanel1Layout);
        teamPanel1Layout.setHorizontalGroup(
            teamPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanel1Layout.createSequentialGroup()
                .add(teamPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(teamNumber1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pointsPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(penaltiesBox1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(teamPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(commentsLabel1)
                    .add(commentsPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        teamPanel1Layout.setVerticalGroup(
            teamPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanel1Layout.createSequentialGroup()
                .add(teamPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(teamNumber1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(commentsLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(teamPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, commentsPane1)
                    .add(teamPanel1Layout.createSequentialGroup()
                        .add(pointsPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(penaltiesBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        teamPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));

        teamNumber2.setText("Team ##");
        teamNumber2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamNumber2MouseClicked(evt);
            }
        });

        pointsPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Points"));

        autoPoints3.setText("Autonomous");
        autoPoints3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoPoints3MouseClicked(evt);
            }
        });

        endPoints3.setText("End Game");
        endPoints3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endPoints3MouseClicked(evt);
            }
        });

        mainPoints3.setText("Main Game");
        mainPoints3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPoints3MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pointsPanel2Layout = new org.jdesktop.layout.GroupLayout(pointsPanel2);
        pointsPanel2.setLayout(pointsPanel2Layout);
        pointsPanel2Layout.setHorizontalGroup(
            pointsPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pointsPanel2Layout.createSequentialGroup()
                .add(autoPoints3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(endPoints3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(pointsPanel2Layout.createSequentialGroup()
                .add(51, 51, 51)
                .add(mainPoints3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pointsPanel2Layout.setVerticalGroup(
            pointsPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pointsPanel2Layout.createSequentialGroup()
                .add(pointsPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(autoPoints3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(endPoints3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainPoints3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        penaltiesBox2.setText("Penalties");
        penaltiesBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penaltiesBox2MouseClicked(evt);
            }
        });

        comments2.setColumns(20);
        comments2.setLineWrap(true);
        comments2.setRows(5);
        commentsPane2.setViewportView(comments2);

        commentsLabel2.setText("Additional Comments");

        org.jdesktop.layout.GroupLayout teamPanel2Layout = new org.jdesktop.layout.GroupLayout(teamPanel2);
        teamPanel2.setLayout(teamPanel2Layout);
        teamPanel2Layout.setHorizontalGroup(
            teamPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanel2Layout.createSequentialGroup()
                .add(teamPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(teamNumber2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pointsPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(penaltiesBox2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(teamPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(commentsLabel2)
                    .add(commentsPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        teamPanel2Layout.setVerticalGroup(
            teamPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanel2Layout.createSequentialGroup()
                .add(teamPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(teamNumber2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(commentsLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(teamPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, commentsPane2)
                    .add(teamPanel2Layout.createSequentialGroup()
                        .add(pointsPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(penaltiesBox2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        teamPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        teamNumber3.setText("Team ##");
        teamNumber3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamNumber3MouseClicked(evt);
            }
        });

        pointsPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Points"));

        autoPoints5.setText("Autonomous");
        autoPoints5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoPoints5MouseClicked(evt);
            }
        });

        endPoints5.setText("End Game");
        endPoints5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endPoints5MouseClicked(evt);
            }
        });

        mainPoints5.setText("Main Game");
        mainPoints5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPoints5MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pointsPanel3Layout = new org.jdesktop.layout.GroupLayout(pointsPanel3);
        pointsPanel3.setLayout(pointsPanel3Layout);
        pointsPanel3Layout.setHorizontalGroup(
            pointsPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pointsPanel3Layout.createSequentialGroup()
                .add(autoPoints5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(endPoints5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(pointsPanel3Layout.createSequentialGroup()
                .add(51, 51, 51)
                .add(mainPoints5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pointsPanel3Layout.setVerticalGroup(
            pointsPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pointsPanel3Layout.createSequentialGroup()
                .add(pointsPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(autoPoints5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(endPoints5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainPoints5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        penaltiesBox3.setText("Penalties");
        penaltiesBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penaltiesBox3MouseClicked(evt);
            }
        });

        comments3.setColumns(20);
        comments3.setLineWrap(true);
        comments3.setRows(5);
        commentsPane3.setViewportView(comments3);

        commentsLabel3.setText("Additional Comments");

        org.jdesktop.layout.GroupLayout teamPanel3Layout = new org.jdesktop.layout.GroupLayout(teamPanel3);
        teamPanel3.setLayout(teamPanel3Layout);
        teamPanel3Layout.setHorizontalGroup(
            teamPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanel3Layout.createSequentialGroup()
                .add(teamPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(teamNumber3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pointsPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(penaltiesBox3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(teamPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(commentsLabel3)
                    .add(commentsPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        teamPanel3Layout.setVerticalGroup(
            teamPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanel3Layout.createSequentialGroup()
                .add(teamPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(teamNumber3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(commentsLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(teamPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, commentsPane3)
                    .add(teamPanel3Layout.createSequentialGroup()
                        .add(pointsPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(penaltiesBox3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        teamPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        teamNumber4.setText("Team ##");
        teamNumber4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamNumber4MouseClicked(evt);
            }
        });

        pointsPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Points"));

        autoPoints6.setText("Autonomous");
        autoPoints6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoPoints6MouseClicked(evt);
            }
        });

        endPoints6.setText("End Game");
        endPoints6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endPoints6MouseClicked(evt);
            }
        });

        mainPoints6.setText("Main Game");
        mainPoints6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPoints6MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pointsPanel4Layout = new org.jdesktop.layout.GroupLayout(pointsPanel4);
        pointsPanel4.setLayout(pointsPanel4Layout);
        pointsPanel4Layout.setHorizontalGroup(
            pointsPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pointsPanel4Layout.createSequentialGroup()
                .add(autoPoints6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(endPoints6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(pointsPanel4Layout.createSequentialGroup()
                .add(51, 51, 51)
                .add(mainPoints6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pointsPanel4Layout.setVerticalGroup(
            pointsPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pointsPanel4Layout.createSequentialGroup()
                .add(pointsPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(autoPoints6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(endPoints6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainPoints6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        penaltiesBox4.setText("Penalties");
        penaltiesBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penaltiesBox4MouseClicked(evt);
            }
        });

        comments4.setColumns(20);
        comments4.setLineWrap(true);
        comments4.setRows(5);
        commentsPane4.setViewportView(comments4);

        commentsLabel4.setText("Additional Comments");

        org.jdesktop.layout.GroupLayout teamPanel4Layout = new org.jdesktop.layout.GroupLayout(teamPanel4);
        teamPanel4.setLayout(teamPanel4Layout);
        teamPanel4Layout.setHorizontalGroup(
            teamPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanel4Layout.createSequentialGroup()
                .add(teamPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(teamNumber4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pointsPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(penaltiesBox4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(teamPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(commentsLabel4)
                    .add(commentsPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        teamPanel4Layout.setVerticalGroup(
            teamPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanel4Layout.createSequentialGroup()
                .add(teamPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(teamNumber4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(commentsLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(teamPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, commentsPane4)
                    .add(teamPanel4Layout.createSequentialGroup()
                        .add(pointsPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(penaltiesBox4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        teamPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 3));

        teamNumber5.setText("Team ##");
        teamNumber5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teamNumber5MouseClicked(evt);
            }
        });

        pointsPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Points"));

        autoPoints7.setText("Autonomous");
        autoPoints7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                autoPoints7MouseClicked(evt);
            }
        });

        endPoints7.setText("End Game");
        endPoints7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endPoints7MouseClicked(evt);
            }
        });

        mainPoints7.setText("Main Game");
        mainPoints7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPoints7MouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout pointsPanel5Layout = new org.jdesktop.layout.GroupLayout(pointsPanel5);
        pointsPanel5.setLayout(pointsPanel5Layout);
        pointsPanel5Layout.setHorizontalGroup(
            pointsPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pointsPanel5Layout.createSequentialGroup()
                .add(autoPoints7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(endPoints7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(pointsPanel5Layout.createSequentialGroup()
                .add(51, 51, 51)
                .add(mainPoints7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pointsPanel5Layout.setVerticalGroup(
            pointsPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pointsPanel5Layout.createSequentialGroup()
                .add(pointsPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(autoPoints7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(endPoints7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mainPoints7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        penaltiesBox5.setText("Penalties");
        penaltiesBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penaltiesBox5MouseClicked(evt);
            }
        });

        comments5.setColumns(20);
        comments5.setLineWrap(true);
        comments5.setRows(5);
        commentsPane5.setViewportView(comments5);

        commentsLabel5.setText("Additional Comments");

        org.jdesktop.layout.GroupLayout teamPanel5Layout = new org.jdesktop.layout.GroupLayout(teamPanel5);
        teamPanel5.setLayout(teamPanel5Layout);
        teamPanel5Layout.setHorizontalGroup(
            teamPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanel5Layout.createSequentialGroup()
                .add(teamPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(teamNumber5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(pointsPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(penaltiesBox5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(teamPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(commentsLabel5)
                    .add(commentsPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        teamPanel5Layout.setVerticalGroup(
            teamPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(teamPanel5Layout.createSequentialGroup()
                .add(teamPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(teamNumber5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(commentsLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(teamPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, commentsPane5)
                    .add(teamPanel5Layout.createSequentialGroup()
                        .add(pointsPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(penaltiesBox5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        formatOption.setText("Format");
        formatOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatOptionActionPerformed(evt);
            }
        });
        fileMenu.add(formatOption);

        commentsOption.setText("Comments");
        commentsOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commentsOptionActionPerformed(evt);
            }
        });
        fileMenu.add(commentsOption);

        aboutOption.setText("About");
        aboutOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutOptionActionPerformed(evt);
            }
        });
        fileMenu.add(aboutOption);

        menu.add(fileMenu);

        editMenu.setText("Edit");

        clearOption.setText("Clear Fields");
        clearOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearOptionActionPerformed(evt);
            }
        });
        editMenu.add(clearOption);

        testOption.setText("Test Data Entry");
        testOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testOptionActionPerformed(evt);
            }
        });
        editMenu.add(testOption);

        menu.add(editMenu);

        setJMenuBar(menu);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(teamPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(teamPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(teamPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(teamPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(teamPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(teamPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(roundPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(143, 143, 143)
                        .add(submitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(teamPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(teamPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(teamPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(teamPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(teamPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(teamPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(roundPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(submitButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // All of these methods with the ".setText(null)" remove the content from a feild if it is the
    // default filler from a mouse click (sometimes double click)
    private void teamNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamNumberMouseClicked
        // TODO add your handling code here:
        if(teamNumber.getText().equals(teamNumberDText))
        {
            teamNumber.setText(null);
        }

    }//GEN-LAST:event_teamNumberMouseClicked

    private void autoPointsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoPointsMouseClicked
        // TODO add your handling code here:
        if(autoPoints.getText().equals(autoPointsDText))
        {
            autoPoints.setText(null);
        }

    }//GEN-LAST:event_autoPointsMouseClicked

    private void endPointsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endPointsMouseClicked
        // TODO add your handling code here:
        if(endPoints.getText().equals(endPointsDText))
        {
            endPoints.setText(null);
        }

    }//GEN-LAST:event_endPointsMouseClicked

    private void mainPointsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPointsMouseClicked
        // TODO add your handling code here:
        if(mainPoints.getText().equals(mainPointsDText))
        {
            mainPoints.setText(null);
        }

    }//GEN-LAST:event_mainPointsMouseClicked

    private void penaltiesBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penaltiesBoxMouseClicked
        // TODO add your handling code here:
        if(penaltiesBox.getText().equals(penaltiesBoxDText))
        {
            penaltiesBox.setText(null);
        }

    }//GEN-LAST:event_penaltiesBoxMouseClicked

    private void teamNumber1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamNumber1MouseClicked
        // TODO add your handling code here:
        if(teamNumber1.getText().equals(teamNumberDText))
        {
            teamNumber1.setText(null);
        }

    }//GEN-LAST:event_teamNumber1MouseClicked

    private void autoPoints2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoPoints2MouseClicked
        // TODO add your handling code here:
        if(autoPoints2.getText().equals(autoPointsDText))
        {
            autoPoints2.setText(null);
        }

    }//GEN-LAST:event_autoPoints2MouseClicked

    private void endPoints2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endPoints2MouseClicked
        // TODO add your handling code here:
        if(endPoints2.getText().equals(endPointsDText))
        {
            endPoints2.setText(null);
        }

    }//GEN-LAST:event_endPoints2MouseClicked

    private void mainPoints2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPoints2MouseClicked
        // TODO add your handling code here:
        if(mainPoints2.getText().equals(mainPointsDText))
        {
            mainPoints2.setText(null);
        }

    }//GEN-LAST:event_mainPoints2MouseClicked

    private void penaltiesBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penaltiesBox1MouseClicked
        // TODO add your handling code here:
        if(penaltiesBox1.getText().equals(penaltiesBoxDText))
        {
            penaltiesBox1.setText(null);
        }

    }//GEN-LAST:event_penaltiesBox1MouseClicked

    private void teamNumber2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamNumber2MouseClicked
        // TODO add your handling code here:
        if(teamNumber2.getText().equals(teamNumberDText))
        {
            teamNumber2.setText(null);
        }

    }//GEN-LAST:event_teamNumber2MouseClicked

    private void autoPoints3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoPoints3MouseClicked
        // TODO add your handling code here:
        if(autoPoints3.getText().equals(autoPointsDText))
        {
            autoPoints3.setText(null);
        }


    }//GEN-LAST:event_autoPoints3MouseClicked

    private void endPoints3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endPoints3MouseClicked
        // TODO add your handling code here:
        if(endPoints3.getText().equals(endPointsDText))
        {
            endPoints3.setText(null);
        }

    }//GEN-LAST:event_endPoints3MouseClicked

    private void mainPoints3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPoints3MouseClicked
        // TODO add your handling code here:
        if(mainPoints3.getText().equals(mainPointsDText))
        {
            mainPoints3.setText(null);
        }

    }//GEN-LAST:event_mainPoints3MouseClicked

    private void penaltiesBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penaltiesBox2MouseClicked
        // TODO add your handling code here:
        if(penaltiesBox2.getText().equals(penaltiesBoxDText))
        {
            penaltiesBox2.setText(null);
        }

    }//GEN-LAST:event_penaltiesBox2MouseClicked

    private void teamNumber3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamNumber3MouseClicked
        // TODO add your handling code here:
        if(teamNumber3.getText().equals(teamNumberDText))
        {
            teamNumber3.setText(null);
        }

    }//GEN-LAST:event_teamNumber3MouseClicked

    private void autoPoints5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoPoints5MouseClicked
        // TODO add your handling code here:
        if(autoPoints5.getText().equals(autoPointsDText))
        {
            autoPoints5.setText(null);
        }


    }//GEN-LAST:event_autoPoints5MouseClicked

    private void endPoints5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endPoints5MouseClicked
        // TODO add your handling code here:
        if(endPoints5.getText().equals(endPointsDText))
        {
            endPoints5.setText(null);
        }

    }//GEN-LAST:event_endPoints5MouseClicked

    private void mainPoints5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPoints5MouseClicked
        // TODO add your handling code here:
        if(mainPoints5.getText().equals(mainPointsDText))
        {
            mainPoints5.setText(null);
        }

    }//GEN-LAST:event_mainPoints5MouseClicked

    private void penaltiesBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penaltiesBox3MouseClicked
        // TODO add your handling code here:
        if(penaltiesBox3.getText().equals(penaltiesBoxDText))
        {
            penaltiesBox3.setText(null);
        }

    }//GEN-LAST:event_penaltiesBox3MouseClicked

    private void teamNumber4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamNumber4MouseClicked
        // TODO add your handling code here:
        if(teamNumber4.getText().equals(teamNumberDText))
        {
            teamNumber4.setText(null);
        }

    }//GEN-LAST:event_teamNumber4MouseClicked

    private void autoPoints6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoPoints6MouseClicked
        // TODO add your handling code here:
        if(autoPoints6.getText().equals(autoPointsDText))
        {
            autoPoints6.setText(null);
        }


    }//GEN-LAST:event_autoPoints6MouseClicked

    private void endPoints6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endPoints6MouseClicked
        // TODO add your handling code here:
        if(endPoints6.getText().equals(endPointsDText))
        {
            endPoints6.setText(null);
        }

    }//GEN-LAST:event_endPoints6MouseClicked

    private void mainPoints6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPoints6MouseClicked
        // TODO add your handling code here:
        if(mainPoints6.getText().equals(mainPointsDText))
        {
            mainPoints6.setText(null);
        }

    }//GEN-LAST:event_mainPoints6MouseClicked

    private void penaltiesBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penaltiesBox4MouseClicked
        // TODO add your handling code here:
        if(penaltiesBox4.getText().equals(penaltiesBoxDText))
        {
            penaltiesBox4.setText(null);
        }

    }//GEN-LAST:event_penaltiesBox4MouseClicked

    private void teamNumber5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teamNumber5MouseClicked
        // TODO add your handling code here:
        if(teamNumber5.getText().equals(teamNumberDText))
        {
            teamNumber5.setText(null);
        }

    }//GEN-LAST:event_teamNumber5MouseClicked

    private void autoPoints7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_autoPoints7MouseClicked
        // TODO add your handling code here:
        if(autoPoints7.getText().equals(autoPointsDText))
        {
            autoPoints7.setText(null);
        }


    }//GEN-LAST:event_autoPoints7MouseClicked

    private void endPoints7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endPoints7MouseClicked
        // TODO add your handling code here:
        if(endPoints7.getText().equals(endPointsDText))
        {
            endPoints7.setText(null);
        }

    }//GEN-LAST:event_endPoints7MouseClicked

    private void mainPoints7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPoints7MouseClicked
        // TODO add your handling code here:
        if(mainPoints7.getText().equals(mainPointsDText))
        {
            mainPoints7.setText(null);
        }
        
    }//GEN-LAST:event_mainPoints7MouseClicked

    private void penaltiesBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penaltiesBox5MouseClicked
        // TODO add your handling code here:
        if(penaltiesBox5.getText().equals(penaltiesBoxDText))
        {
            penaltiesBox5.setText(null);
        }
        
    }//GEN-LAST:event_penaltiesBox5MouseClicked

    // This method is called when the submit button is pressed
    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            // Set the flag to true
            submitted = true;

            // Store Team numbers
            //System.out.println("Storing Teams...");
            teamNumberArray[0] = Integer.parseInt(teamNumber.getText());
            teamNumberArray[1] = Integer.parseInt(teamNumber1.getText());
            teamNumberArray[2] = Integer.parseInt(teamNumber2.getText());
            teamNumberArray[3] = Integer.parseInt(teamNumber3.getText());
            teamNumberArray[4] = Integer.parseInt(teamNumber4.getText());
            teamNumberArray[5] = Integer.parseInt(teamNumber5.getText());

            // Store scores for Team #1
            //System.out.println("Storing Scores for Team #1");
            teamScoreArray[0][0] = Integer.parseInt(autoPoints.getText());
            teamScoreArray[1][0] = Integer.parseInt(mainPoints.getText());
            teamScoreArray[2][0] = Integer.parseInt(endPoints.getText());

            // Store scores for Team #2
            //System.out.println("Storing Scores for Team #2");
            teamScoreArray[0][1] = Integer.parseInt(autoPoints2.getText());
            teamScoreArray[1][1] = Integer.parseInt(mainPoints2.getText());
            teamScoreArray[2][1] = Integer.parseInt(endPoints2.getText());

            // Store scores for Team #3
            //System.out.println("Storing Scores for Team #3");
            teamScoreArray[0][2] = Integer.parseInt(autoPoints3.getText());
            teamScoreArray[1][2] = Integer.parseInt(mainPoints3.getText());
            teamScoreArray[2][2] = Integer.parseInt(endPoints3.getText());

            // Store scores for Team #4
            //System.out.println("Storing Scores for Team #4");
            teamScoreArray[0][3] = Integer.parseInt(autoPoints5.getText());
            teamScoreArray[1][3] = Integer.parseInt(mainPoints5.getText());
            teamScoreArray[2][3] = Integer.parseInt(endPoints5.getText());

            // Store scores for Team #5
            //System.out.println("Storing Scores for Team #5");
            teamScoreArray[0][4] = Integer.parseInt(autoPoints6.getText());
            teamScoreArray[1][4] = Integer.parseInt(mainPoints6.getText());
            teamScoreArray[2][4] = Integer.parseInt(endPoints6.getText());

            // Store scores for Team #6
            //System.out.println("Storing Scores for Team #6");
            teamScoreArray[0][5] = Integer.parseInt(autoPoints7.getText());
            teamScoreArray[1][5] = Integer.parseInt(mainPoints7.getText());
            teamScoreArray[2][5] = Integer.parseInt(endPoints7.getText());

            // Store penalties for all teams
            //System.out.println("Storing Penalties...");
            teamPenaltiesArray[0] = penaltiesBox.getText();
            teamPenaltiesArray[1] = penaltiesBox1.getText();
            teamPenaltiesArray[2] = penaltiesBox2.getText();
            teamPenaltiesArray[3] = penaltiesBox3.getText();
            teamPenaltiesArray[4] = penaltiesBox4.getText();
            teamPenaltiesArray[5] = penaltiesBox5.getText();

            // Store comments for all teams
            //System.out.println("Storing Comments...");
            commentsArray[0] = comments.getText();
            commentsArray[1] = comments1.getText();
            commentsArray[2] = comments2.getText();
            commentsArray[3] = comments3.getText();
            commentsArray[4] = comments4.getText();
            commentsArray[5] = comments5.getText();

            // Store the current match
            currentMatch = Integer.parseInt(roundInput.getText());

            // If the current match is less than or equal to 0, throw an exception
            if(currentMatch <= 0)
            {
                throw new Exception();
            }

            // Incriment the current match
            currentMatch++;

            // reset all the feilds!
            resetFields();

            // Store the new Match number
            roundInput.setText(Integer.toString(currentMatch));

            // If the penalties for a team equal null or the default text, replace the penalties with "none"
            for(int i = 0; i < 6; i++)
            {
                if(teamPenaltiesArray[i].equals(penaltiesBoxDText) || teamPenaltiesArray[i].equals(""))
                {
                    teamPenaltiesArray[i] = "none";
                }
            }
        }

        // If a feild was empty or something failed, reset the submitted button, and tell the console
        catch (Exception e)
        {
            System.out.println("Bad Submission!");
            submitted = false;
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    // If the Format menu option is clicked, pull up the FormatGUI
    private void formatOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatOptionActionPerformed
        // TODO add your handling code here:
        FormatGUI fGUI = new FormatGUI();
    }//GEN-LAST:event_formatOptionActionPerformed

    // If the Comments menu option is clicked, pull up the CommenteTipsGUI
    private void commentsOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commentsOptionActionPerformed
        // TODO add your handling code here:
        CommentsTipsGUI cGUI = new CommentsTipsGUI();
    }//GEN-LAST:event_commentsOptionActionPerformed

    // If the About menu option is clicked, pull up the AboutGUI
    private void aboutOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutOptionActionPerformed
        // TODO add your handling code here:
        AboutGUI aGUI = new AboutGUI();
    }//GEN-LAST:event_aboutOptionActionPerformed

    // If the Clear Feilds menu option is clicked, reset all of the feilds
    private void clearOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearOptionActionPerformed
        // TODO add your handling code here:
        resetFields();
    }//GEN-LAST:event_clearOptionActionPerformed

    // Debugging option
    // If the Test Data Entry option is clicked, fill the feilds
    private void testOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testOptionActionPerformed
        // TODO add your handling code here:
        fillFields();
    }//GEN-LAST:event_testOptionActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataEntryGUI().setVisible(true);
            }
        });
    }

    // Return methods for the data
    public int[] getTeamNumbers()
    {
        return teamNumberArray;
    }

    public int[][] getScores()
    {
        return teamScoreArray;
    }

    public String[] getPenalties()
    {
        return teamPenaltiesArray;
    }

    public int getMatch()
    {
        return currentMatch - 1;
    }

    public String[] getComments()
    {
        return commentsArray;
    }

    public boolean getSubmittedFlag() throws InterruptedException
    {
        // The sleep helps the computer think
        Thread.currentThread().sleep(10);
        return submitted;
    }

    public void resetSubmittedFlag()
    {
        submitted = false;
    }

    // Clears all f the feilds
    public void resetFields()
    {
        autoPoints.setText(null);
        autoPoints2.setText(null);
        autoPoints3.setText(null);
        autoPoints5.setText(null);
        autoPoints6.setText(null);
        autoPoints7.setText(null);
        comments.setText(null);
        comments1.setText(null);
        comments2.setText(null);
        comments3.setText(null);
        comments4.setText(null);
        comments5.setText(null);
        endPoints.setText(null);
        endPoints2.setText(null);
        endPoints3.setText(null);
        endPoints5.setText(null);
        endPoints6.setText(null);
        endPoints7.setText(null);
        mainPoints.setText(null);
        mainPoints2.setText(null);
        mainPoints3.setText(null);
        mainPoints5.setText(null);
        mainPoints6.setText(null);
        mainPoints7.setText(null);
        penaltiesBox.setText(null);
        penaltiesBox1.setText(null);
        penaltiesBox2.setText(null);
        penaltiesBox3.setText(null);
        penaltiesBox4.setText(null);
        penaltiesBox5.setText(null);
        teamNumber.setText(null);
        teamNumber1.setText(null);
        teamNumber2.setText(null);
        teamNumber3.setText(null);
        teamNumber4.setText(null);
        teamNumber5.setText(null);
    }

    // Fills many of the fields with random numbers based on the cap for each feild
    public void fillFields()
    {
        autoPoints.setText(Integer.toString(new Random().nextInt(RAND_AUTO_POINT_CAP)));
        autoPoints2.setText(Integer.toString(new Random().nextInt(RAND_AUTO_POINT_CAP)));
        autoPoints3.setText(Integer.toString(new Random().nextInt(RAND_AUTO_POINT_CAP)));
        autoPoints5.setText(Integer.toString(new Random().nextInt(RAND_AUTO_POINT_CAP)));
        autoPoints6.setText(Integer.toString(new Random().nextInt(RAND_AUTO_POINT_CAP)));
        autoPoints7.setText(Integer.toString(new Random().nextInt(RAND_AUTO_POINT_CAP)));
        endPoints.setText(Integer.toString(new Random().nextInt(RAND_END_POINT_CAP)));
        endPoints2.setText(Integer.toString(new Random().nextInt(RAND_END_POINT_CAP)));
        endPoints3.setText(Integer.toString(new Random().nextInt(RAND_END_POINT_CAP)));
        endPoints5.setText(Integer.toString(new Random().nextInt(RAND_END_POINT_CAP)));
        endPoints6.setText(Integer.toString(new Random().nextInt(RAND_END_POINT_CAP)));
        endPoints7.setText(Integer.toString(new Random().nextInt(RAND_END_POINT_CAP)));
        mainPoints.setText(Integer.toString(new Random().nextInt(RAND_MAIN_POINT_CAP)));
        mainPoints2.setText(Integer.toString(new Random().nextInt(RAND_MAIN_POINT_CAP)));
        mainPoints3.setText(Integer.toString(new Random().nextInt(RAND_MAIN_POINT_CAP)));
        mainPoints5.setText(Integer.toString(new Random().nextInt(RAND_MAIN_POINT_CAP)));
        mainPoints6.setText(Integer.toString(new Random().nextInt(RAND_MAIN_POINT_CAP)));
        mainPoints7.setText(Integer.toString(new Random().nextInt(RAND_MAIN_POINT_CAP)));
        penaltiesBox.setText(penaltiesBoxDText);
        penaltiesBox1.setText(penaltiesBoxDText);
        penaltiesBox2.setText(penaltiesBoxDText);
        penaltiesBox3.setText(penaltiesBoxDText);
        penaltiesBox4.setText(penaltiesBoxDText);
        penaltiesBox5.setText(penaltiesBoxDText);
        teamNumber.setText("2555");
        teamNumber1.setText("2500");
        teamNumber2.setText("111");
        teamNumber3.setText("1816");
        teamNumber4.setText("2169");
        teamNumber5.setText("1337");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutOption;
    private javax.swing.JTextField autoPoints;
    private javax.swing.JTextField autoPoints2;
    private javax.swing.JTextField autoPoints3;
    private javax.swing.JTextField autoPoints5;
    private javax.swing.JTextField autoPoints6;
    private javax.swing.JTextField autoPoints7;
    private javax.swing.JMenuItem clearOption;
    private javax.swing.JTextArea comments;
    private javax.swing.JTextArea comments1;
    private javax.swing.JTextArea comments2;
    private javax.swing.JTextArea comments3;
    private javax.swing.JTextArea comments4;
    private javax.swing.JTextArea comments5;
    private javax.swing.JLabel commentsLabel;
    private javax.swing.JLabel commentsLabel1;
    private javax.swing.JLabel commentsLabel2;
    private javax.swing.JLabel commentsLabel3;
    private javax.swing.JLabel commentsLabel4;
    private javax.swing.JLabel commentsLabel5;
    private javax.swing.JMenuItem commentsOption;
    private javax.swing.JScrollPane commentsPane;
    private javax.swing.JScrollPane commentsPane1;
    private javax.swing.JScrollPane commentsPane2;
    private javax.swing.JScrollPane commentsPane3;
    private javax.swing.JScrollPane commentsPane4;
    private javax.swing.JScrollPane commentsPane5;
    private javax.swing.JMenu editMenu;
    private javax.swing.JTextField endPoints;
    private javax.swing.JTextField endPoints2;
    private javax.swing.JTextField endPoints3;
    private javax.swing.JTextField endPoints5;
    private javax.swing.JTextField endPoints6;
    private javax.swing.JTextField endPoints7;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem formatOption;
    private javax.swing.JTextField mainPoints;
    private javax.swing.JTextField mainPoints2;
    private javax.swing.JTextField mainPoints3;
    private javax.swing.JTextField mainPoints5;
    private javax.swing.JTextField mainPoints6;
    private javax.swing.JTextField mainPoints7;
    private javax.swing.JMenuBar menu;
    private javax.swing.JTextField penaltiesBox;
    private javax.swing.JTextField penaltiesBox1;
    private javax.swing.JTextField penaltiesBox2;
    private javax.swing.JTextField penaltiesBox3;
    private javax.swing.JTextField penaltiesBox4;
    private javax.swing.JTextField penaltiesBox5;
    private javax.swing.JPanel pointsPanel;
    private javax.swing.JPanel pointsPanel1;
    private javax.swing.JPanel pointsPanel2;
    private javax.swing.JPanel pointsPanel3;
    private javax.swing.JPanel pointsPanel4;
    private javax.swing.JPanel pointsPanel5;
    private javax.swing.JTextField roundInput;
    private javax.swing.JLabel roundLabel;
    private javax.swing.JPanel roundPanel;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField teamNumber;
    private javax.swing.JTextField teamNumber1;
    private javax.swing.JTextField teamNumber2;
    private javax.swing.JTextField teamNumber3;
    private javax.swing.JTextField teamNumber4;
    private javax.swing.JTextField teamNumber5;
    private javax.swing.JPanel teamPanel;
    private javax.swing.JPanel teamPanel1;
    private javax.swing.JPanel teamPanel2;
    private javax.swing.JPanel teamPanel3;
    private javax.swing.JPanel teamPanel4;
    private javax.swing.JPanel teamPanel5;
    private javax.swing.JMenuItem testOption;
    // End of variables declaration//GEN-END:variables

}
